### Process sgRNA read count and library data
1. for TKOv3, integrate read count data with refined TKOv3 library
2. remove all rows without sgRNA sequences
3. export data in a new format

In [2]:
import pandas as pd

In [9]:
read_count = pd.read_csv("../../data/read_count_data/Dataset_S2_readcounts_olivieri_paper.txt", sep="\t")
# read_count = read_count.set_index("sgRNA")
read_count

,sgRNA,Gene,S01_Cisplatin-2_T18_A,S01_Cisplatin-2_T18_B,S01_NT_T18_A,S01_NT_T18_B,S02_Bleomycin_T15_A,S02_Bleomycin_T15_B,S02_NT_T15_A,S02_NT_T15_B,...,S07_T0,S12_BPDE_T18_A,S12_BPDE_T18_B,S12_HU_acute_T18_A,S12_HU_acute_T18_B,S12_NT_T18_A,S12_NT_T18_B,S12_PladB_T18_A,S12_PladB_T18_B,S12_T0
0,chr1:100133208-100133227_PALMD_-,PALMD,916,1154,1194,1115,1068,907,897,738,...,2145,504,339,636,446,2428,1450,1389,1187,1667
1,chr1:100133210-100133229_PALMD_+,PALMD,219,362,282,460,506,293,419,255,...,561,188,83,222,111,797,187,532,285,318
2,chr1:100152265-100152284_PALMD_+,PALMD,259,163,381,227,242,222,211,461,...,298,145,78,313,88,677,208,612,201,385
3,chr1:100154492-100154511_PALMD_+,PALMD,331,292,439,368,577,347,537,411,...,887,277,203,312,217,1217,408,735,415,718
4,chr1:100203726-100203745_FRRS1_+,FRRS1,165,143,205,164,111,177,109,167,...,604,185,52,334,100,649,182,451,163,699
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71085,luciferase:45-64_luciferase_+,luciferase,677,1088,782,866,1155,659,680,726,...,1310,450,283,525,326,1632,858,961,989,1088
71086,luciferase:533-552_luciferase_-,luciferase,1067,1147,1227,1121,1284,1007,1271,928,...,1791,466,334,681,336,2076,624,1591,885,1564
71087,luciferase:649-668_luciferase_-,luciferase,774,699,807,763,1202,950,841,747,...,1270,262,245,420,248,1328,645,867,695,1393
71088,luciferase:83-102_luciferase_+,luciferase,46,20,51,17,96,117,82,105,...,201,20,68,40,58,97,115,132,239,166
71089,luciferase:970-989_luciferase_-,luciferase,235,438,348,470,500,177,241,156,...,546,112,129,253,132,545,312,318,208,410

In [6]:
read_count["sgRNA"]

0        chr1:100133208-100133227_PALMD_-
1        chr1:100133210-100133229_PALMD_+
2        chr1:100152265-100152284_PALMD_+
3        chr1:100154492-100154511_PALMD_+
4        chr1:100203726-100203745_FRRS1_+
                       ...
71085       luciferase:45-64_luciferase_+
71086     luciferase:533-552_luciferase_-
71087     luciferase:649-668_luciferase_-
71088      luciferase:83-102_luciferase_+
71089     luciferase:970-989_luciferase_-
Name: sgRNA, Length: 71090, dtype: object

In [8]:
# select for refined sgRNA library
read_count['spacer'] = read_count['sgRNA'].str.extract(r'_(.*)$')

col = read_count.pop('spacer')
read_count.insert(1, 'spacer', col)
read_count

,GENE,spacer,RPE1_T0,RPE1_T3A_CTRL_LOPRIMER,RPE1_T3A_CTRL,RPE1_T3A_ENTI_LOPRIMER,RPE1_T3A_ENTI,RPE1_T3A_GEMC,RPE1_T3A_VINC,RPE1_T3B_CTRL,RPE1_T3B_ENTI,RPE1_T3B_GEMC,RPE1_T3B_VINC
sgRNA,,,,,,,,,,,,,
A1BG_ACTGGCGCCATCGAGAGCCA,A1BG,NaN,164,83,93,33,50,105,39,44,118,33,77
A1BG_CAAGAGAAAGACCACGAGCA,A1BG,NaN,492,416,288,275,262,277,286,222,401,216,228
A1BG_GCTCAGCTGGGTCCATCCTG,A1BG,NaN,258,54,49,38,25,101,28,5,57,52,32
A1BG_GTCGAGCTGATTCTGAGCGA,A1BG,NaN,487,668,360,462,307,353,278,290,565,193,209
A1CF_AGTTATGTTAGGTATACCCG,A1CF,NaN,149,242,133,193,187,165,133,140,379,87,189
...,...,...,...,...,...,...,...,...,...,...,...,...,...
luciferase_GGTCTTCCCGACGATGACGC,luciferase,NaN,320,345,160,154,108,150,146,59,167,112,82
luciferase_TATCGATTCCAATTCAGCGG,luciferase,NaN,298,265,183,359,339,246,234,153,317,220,195
luciferase_TATTCTGATTACACCCGAGG,luciferase,NaN,384,603,395,372,361,353,329,243,482,301,345
luciferase_TCTAGAGGATAGAATGGCGC,luciferase,NaN,399,414,266,228,164,244,165,138,418,202,158
luciferase_TTTGTGGACGAAGTACCGAA,luciferase,NaN,392,396,340,196,203,219,203,140,283,262,148

In [3]:
# check that number of unique spacer sequence match with the number of rows
read_count["spacer"].nunique()

71090

In [4]:
library = pd.read_csv("../../data/library_data/refined_library/tkov3_guide_sequence_61K_refined.tsv", sep = "\t", header=None)
library = library.rename(columns={0: "sgRNA", 1: "spacer", 2: "gene"})
library["spacer"]

0        AGCGATGCGACCCTCCGGGA
1        GATGTTCAATAACTGTGAGG
2        ATAACCAGCCACCTCCTGGA
3        TGTGATCCAAGCTGTCCCAA
4        CAGCTGGCGTAATAGCGAAG
                 ...
61135    GACGACGCAGCAGTCGCCGG
61136    AAAGACAACACCCTACAGTG
61137    GTACATATGAGCCCACACAT
61138    ATTGTAGATCACCAGAACAC
61139    TAACAGGTTACAGGGAACAA
Name: spacer, Length: 61140, dtype: object

In [5]:
# only select read count that has sgRNA sequences data from refined library
read_count = read_count[read_count['spacer'].isin(library["spacer"])]
read_count

,sgRNA,spacer,GENE,RPE1_T0,RPE1_T3A_CTRL_LOPRIMER,RPE1_T3A_CTRL,RPE1_T3A_ENTI_LOPRIMER,RPE1_T3A_ENTI,RPE1_T3A_GEMC,RPE1_T3A_VINC,RPE1_T3B_CTRL,RPE1_T3B_ENTI,RPE1_T3B_GEMC,RPE1_T3B_VINC
0,A1BG_ACTGGCGCCATCGAGAGCCA,ACTGGCGCCATCGAGAGCCA,A1BG,164,83,93,33,50,105,39,44,118,33,77
1,A1BG_CAAGAGAAAGACCACGAGCA,CAAGAGAAAGACCACGAGCA,A1BG,492,416,288,275,262,277,286,222,401,216,228
2,A1BG_GCTCAGCTGGGTCCATCCTG,GCTCAGCTGGGTCCATCCTG,A1BG,258,54,49,38,25,101,28,5,57,52,32
3,A1BG_GTCGAGCTGATTCTGAGCGA,GTCGAGCTGATTCTGAGCGA,A1BG,487,668,360,462,307,353,278,290,565,193,209
4,A1CF_AGTTATGTTAGGTATACCCG,AGTTATGTTAGGTATACCCG,A1CF,149,242,133,193,187,165,133,140,379,87,189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71085,luciferase_GGTCTTCCCGACGATGACGC,GGTCTTCCCGACGATGACGC,luciferase,320,345,160,154,108,150,146,59,167,112,82
71086,luciferase_TATCGATTCCAATTCAGCGG,TATCGATTCCAATTCAGCGG,luciferase,298,265,183,359,339,246,234,153,317,220,195
71087,luciferase_TATTCTGATTACACCCGAGG,TATTCTGATTACACCCGAGG,luciferase,384,603,395,372,361,353,329,243,482,301,345
71088,luciferase_TCTAGAGGATAGAATGGCGC,TCTAGAGGATAGAATGGCGC,luciferase,399,414,266,228,164,244,165,138,418,202,158
71089,luciferase_TTTGTGGACGAAGTACCGAA,TTTGTGGACGAAGTACCGAA,luciferase,392,396,340,196,203,219,203,140,283,262,148

In [6]:
# remove the spacer column and export the file in a delimited format
read_count.pop('spacer')
read_count.to_csv("../../data/sgrna_lfc_data/tkov3_data/refined_matrix-reads-by-gRNA-RPE1-drugZ.txt", sep = "\t", index = None)